In [1]:
1+1

2

## list(리스트)

In [45]:
a= 2
b= [3,1,4,1,5,9]
c = [1,3,4,0]

In [24]:
format(b)


'[3, 1, 4, 1, 5, 9]'

In [17]:
b[0]

3

In [18]:
len(b) # b라는 리스트의 길이

6

In [19]:
len(a)

TypeError: object of type 'int' has no len()

In [21]:
b[-1] # 음수는 끝부터 세는 것

9

In [22]:
b[0]+b[1]

4

In [25]:
b[0]+c[1]

6

In [26]:
b+b

[3, 1, 4, 1, 5, 9, 3, 1, 4, 1, 5, 9]

In [29]:
c+b, b+c # b+c =/ C+b

([1, 3, 4, 0, 3, 1, 4, 1, 5, 9], [3, 1, 4, 1, 5, 9, 1, 3, 4, 0])

In [33]:
b*3 # b*3 = bbb

[3, 1, 4, 1, 5, 9, 3, 1, 4, 1, 5, 9, 3, 1, 4, 1, 5, 9]

In [36]:
b[5] = 8 #슬라이스

In [46]:
b

[3, 1, 4, 1, 5, 9]

In [38]:
b[0:5]

[3, 1, 4, 1, 5]

In [39]:
b[2:4]

[4, 1]

##### 만약 리스트에 성분을 추가하고 싶다면?


In [47]:
b.append(2)

In [48]:
b

[3, 1, 4, 1, 5, 9, 2]

##### 만약 리스트에서 어느 성분을 뺴고 출력하고 싶다면?

In [49]:
b.pop(2)

4

In [50]:
b

[3, 1, 1, 5, 9, 2]

In [51]:
b.pop()

2

In [52]:
b

[3, 1, 1, 5, 9]

##### 리스트에서 어느 성분을 지우고 싶다면?

In [54]:
del.b(4)

SyntaxError: invalid syntax (<ipython-input-54-4e6fa09fb590>, line 1)

## Array 

### 리스트보다 훨씬 빠름, 벡터, 행렬, 물리계산에 용이 

In [65]:
import numpy as np
a= [3,1,4,1,5,9]

###import numpy as np - numpy를 np라고 쓸거야!

In [8]:
np.pi, np.exp(1)

(3.141592653589793, 2.718281828459045)

In [57]:
numpy.pi, np.sin(np.pi)

(3.141592653589793, 1.2246467991473532e-16)

In [68]:
b= np.array(a,int)

In [69]:
c = np.array([3,1,4,1,5,9],float)

In [70]:
b, c

(array([3, 1, 4, 1, 5, 9]), array([3., 1., 4., 1., 5., 9.]))

In [71]:
d = np.array([a])

In [72]:
d

array([[3, 1, 4, 1, 5, 9]])

In [78]:
e = np.zeros(6) # 크기 6인 0 array출력
f = np.ones(6)# 크기 6인 1 array출력
g = np.linspace(0,100,6) #linspace(a,b,c) - 크기 c, 시작점 a, 끝점 b인 일정 간격 array 출력

In [79]:
e,f,g

(array([0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1.]),
 array([  0.,  20.,  40.,  60.,  80., 100.]))

In [80]:
np.append(c,2)

array([3., 1., 4., 1., 5., 9., 2.])

### 사칙연산 시 벡터 연산이 가능하다, list에서는 두 리스트가 단순히 더해져서 리스트의 크기가 바뀌었지만, array는 성분끼리의 합이 계산된다.

In [82]:
b+c, b/c

(array([ 6.,  2.,  8.,  2., 10., 18.]), array([1., 1., 1., 1., 1., 1.]))

In [84]:
np.dot(b,c) # 내적 계산

133.0

In [85]:
np.cross(b,c)

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [86]:
a = np.array([[1,2],[3,4]])

In [88]:
a # 행렬

array([[1, 2],
       [3, 4]])

In [90]:
b = np.array([[3,4],[3,1]])

In [91]:
np.dot(a,b)

array([[ 9,  6],
       [21, 16]])

In [92]:
a*b

array([[3, 8],
       [9, 4]])

In [94]:
np. linalg.eig(b) # eigen value 계산

(array([ 5.60555128, -1.60555128]),
 array([[ 0.83791185, -0.65572799],
        [ 0.54580557,  0.75499722]]))

In [98]:
np.linalg.inv(b) # 역행렬 계산

array([[-0.11111111,  0.44444444],
       [ 0.33333333, -0.33333333]])

## list comprehension 

##### list 안에서 for 돌리기

In [100]:
[i*2 for i in [1,2,3]]

[2, 4, 6]

In [102]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [103]:
a= [1,2,3,4,5]

In [104]:
b= [i*5 for i in a]

In [105]:
b

[5, 10, 15, 20, 25]

In [107]:
c= []
for i in a:
    c.append(i*5)

In [108]:
c

[5, 10, 15, 20, 25]

## 문자열 다루기 

### 문자열은 리스트와 비슷하다 

In [109]:
'deep learning'

'deep learning'

In [110]:
'shallow learning'

'shallow learning'

In [113]:
a = 'deep learning'

In [117]:
a[0], a[3], a[4], a[-1]

('d', 'p', ' ', 'g')

In [112]:
'1,2,3,4' # 문자로 취급됨

'1,2,3,4'

In [120]:
b= '3.14'
c= [3,1,4]
d= [1,2,3]

In [121]:
c+d

[3, 1, 4, 1, 2, 3]

In [125]:
b+c # 문자열 + 숫자 불가능

TypeError: can only concatenate str (not "list") to str

In [126]:
a+b # 문자열끼리는 가능

'deep learning3.14'

## 입출력 

In [127]:
print('aaa')


aaa


In [128]:
a= 2
b= 3.14

In [130]:
print(a,b), print([a,b])

2 3.14
[2, 3.14]


(None, None)

In [138]:
f=open("save.txt","w")
a=[]
for i in range(20):
    a.append(i)
a = np.array(a)
a = str(a)
f.write(a)
f.close()

## Function(함수) 

In [139]:
import numpy as np

In [141]:
2**3

8

In [143]:
np.power(2,3)

8

In [144]:
# 3^5를 구하고 싶음
a, b = 3, 5

p = 1
for i in range(0,b):
    p=p*a
print(p)

243


In [145]:
def power(a,b):
    p = 1
    for i in range(0,b):
        p = p*a
    return p

In [146]:
power(3,5)

243

In [147]:
power(2,10)


1024

In [148]:
def calc(a,b):
    return a+b, a-b, a*b, a/b

In [149]:
a= calc(9,3)
a

(12, 6, 27, 3.0)